apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-traces-config
  namespace: alloy 
data:
  config.alloy: |-
    otelcol.receiver.otlp "default" {
      grpc {}
      http {}

      output {
        traces  = [otelcol.processor.batch.default.input]
      }
    }

    otelcol.processor.batch "default" {
      output {
        traces  = [otelcol.exporter.otlp.tempo.input]
      }
    }

    otelcol.exporter.otlp "tempo" {
      client {
        endpoint = "http://tempo-distributor.tempo.svc.cluster.local:4317"
        tls {
          insecure             = true
          insecure_skip_verify = true
        }
      }
    }


